export const LOADING = 'LOADING'

export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'
export const SIGNUP_ERROR = 'SIGNUP_ERROR'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_ERROR = 'LOGIN_ERROR'

export const GET_USER_SUCCESS = 'GET_USER_SUCCESS'
export const GET_USER_ERROR = 'GET_USER_ERROR'

export const REFRESH_SUCCESS = 'REFRESH_SUCCESS'
export const REFRESH_ERROR = 'REFRESH_ERROR'

export const LOGOUT = 'LOGOUT'

export const ADD_NEW_CONTACT_SUCCESS = 'ADD_NEW_CONTACT_SUCCESS'
export const ADD_NEW_CONTACT_ERROR = 'ADD_NEW_CONTACT_ERROR'

export const GET_CONTACTS_SUCCESS = 'GET_CONTACTS_SUCCESS'
export const GET_CONTACTS_ERROR = 'GET_CONTACTS_ERROR'

export const SET_ROOMS = 'SET_ROOMS'
export const SET_CURRENT_ROOM = 'SET_CURRENT_ROOM'
export const SET_MESSAGE = 'SET_MESSAGE'
export const SET_NAME = 'SET_NAME'
